2025-04-09 15:06:02,527 - __main__ - INFO - Starting application on port 5000 with debug=False
2025-04-09 15:08:29,878 - __main__ - INFO - Starting application on port 5050 with debug=False
2025-04-09 15:08:29,918 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5050
 * Running on http://192.168.1.14:5050
2025-04-09 15:08:29,926 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-04-09 15:08:48,458 - devops-assessment-flask-app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\devops-assessment-flask-app.py", line 95, in index
    return render_template('index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2025-04-09 15:08:48,474 - werkzeug - INFO - 127.0.0.1 - - [09/Apr/2025 15:08:48] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-04-09 15:08:48,680 - werkzeug - INFO - 127.0.0.1 - - [09/Apr/2025 15:08:48] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-04-09 15:09:07,635 - devops-assessment-flask-app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\devops-assessment-flask-app.py", line 95, in index
    return render_template('index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Docs\pyApp\venv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2025-04-09 15:09:07,651 - werkzeug - INFO - 127.0.0.1 - - [09/Apr/2025 15:09:07] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-04-09 15:11:38,737 - __main__ - INFO - Starting application on port 5050 with debug=False
2025-04-09 15:11:38,754 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5050
 * Running on http://192.168.1.14:5050
2025-04-09 15:11:38,754 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-04-09 15:11:45,934 - werkzeug - INFO - 127.0.0.1 - - [09/Apr/2025 15:11:45] "GET / HTTP/1.1" 200 -
2025-04-15 20:51:12,261 - __main__ - INFO - Starting application on port 5050 with debug=False
2025-04-15 20:51:13,272 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5050
 * Running on http://192.168.43.91:5050
2025-04-15 20:51:13,282 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-04-17 12:41:57,477 - __main__ - INFO - Starting application on port 5050 with debug=False
2025-04-17 12:41:57,506 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5050
 * Running on http://192.168.1.15:5050
2025-04-17 12:41:57,506 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-04-17 12:42:09,993 - werkzeug - INFO - 127.0.0.1 - - [17/Apr/2025 12:42:09] "GET / HTTP/1.1" 200 -
2025-04-17 12:42:10,327 - werkzeug - INFO - 127.0.0.1 - - [17/Apr/2025 12:42:10] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-04-17 12:42:14,096 - werkzeug - INFO - 127.0.0.1 - - [17/Apr/2025 12:42:14] "GET / HTTP/1.1" 200 -
2025-04-17 12:42:23,855 - werkzeug - INFO - 127.0.0.1 - - [17/Apr/2025 12:42:23] "GET / HTTP/1.1" 200 -
